import { z } from 'zod';
export declare const ConfigSchema: z.ZodObject<{
    githubToken: z.ZodString;
    mode: z.ZodDefault<z.ZodEnum<["rules", "ai"]>>;
    ai: z.ZodDefault<z.ZodObject<{
        provider: z.ZodDefault<z.ZodEnum<["openai", "ollama", "anthropic"]>>;
        apiKey: z.ZodOptional<z.ZodString>;
        baseUrl: z.ZodOptional<z.ZodString>;
        model: z.ZodDefault<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        provider: "openai" | "ollama" | "anthropic";
        model: string;
        apiKey?: string | undefined;
        baseUrl?: string | undefined;
    }, {
        provider?: "openai" | "ollama" | "anthropic" | undefined;
        apiKey?: string | undefined;
        baseUrl?: string | undefined;
        model?: string | undefined;
    }>>;
    maxFailures: z.ZodDefault<z.ZodNumber>;
    minQualityScore: z.ZodDefault<z.ZodNumber>;
    requireConventionalTitle: z.ZodDefault<z.ZodBoolean>;
    blockedTitlePatterns: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    requireDescription: z.ZodDefault<z.ZodBoolean>;
    minDescriptionLength: z.ZodDefault<z.ZodNumber>;
    maxDescriptionLength: z.ZodDefault<z.ZodNumber>;
    requirePrTemplate: z.ZodDefault<z.ZodBoolean>;
    requireConventionalCommits: z.ZodDefault<z.ZodBoolean>;
    maxCommitMessageLength: z.ZodDefault<z.ZodNumber>;
    requireCommitAuthorMatch: z.ZodDefault<z.ZodBoolean>;
    blockedSourceBranches: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    allowedTargetBranches: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    blockedFilePatterns: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    maxFilesChanged: z.ZodDefault<z.ZodNumber>;
    maxAdditions: z.ZodDefault<z.ZodNumber>;
    minAccountAgeDays: z.ZodDefault<z.ZodNumber>;
    detectSpamUsernames: z.ZodDefault<z.ZodBoolean>;
    detectExcessiveComments: z.ZodDefault<z.ZodBoolean>;
    detectHallucinatedImports: z.ZodDefault<z.ZodBoolean>;
    maxEmojiCount: z.ZodDefault<z.ZodNumber>;
    closePr: z.ZodDefault<z.ZodBoolean>;
    addLabel: z.ZodDefault<z.ZodString>;
    commentOnPr: z.ZodDefault<z.ZodBoolean>;
    exemptUsers: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    exemptBots: z.ZodDefault<z.ZodBoolean>;
    exemptDraftPrs: z.ZodDefault<z.ZodBoolean>;
    exemptLabels: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    githubToken: string;
    ai: {
        provider: "openai" | "ollama" | "anthropic";
        model: string;
        apiKey?: string | undefined;
        baseUrl?: string | undefined;
    };
    mode: "rules" | "ai";
    maxFailures: number;
    minQualityScore: number;
    requireConventionalTitle: boolean;
    blockedTitlePatterns: string[];
    requireDescription: boolean;
    minDescriptionLength: number;
    maxDescriptionLength: number;
    requirePrTemplate: boolean;
    requireConventionalCommits: boolean;
    maxCommitMessageLength: number;
    requireCommitAuthorMatch: boolean;
    blockedSourceBranches: string[];
    allowedTargetBranches: string[];
    blockedFilePatterns: string[];
    maxFilesChanged: number;
    maxAdditions: number;
    minAccountAgeDays: number;
    detectSpamUsernames: boolean;
    detectExcessiveComments: boolean;
    detectHallucinatedImports: boolean;
    maxEmojiCount: number;
    closePr: boolean;
    addLabel: string;
    commentOnPr: boolean;
    exemptUsers: string[];
    exemptBots: boolean;
    exemptDraftPrs: boolean;
    exemptLabels: string[];
}, {
    githubToken: string;
    ai?: {
        provider?: "openai" | "ollama" | "anthropic" | undefined;
        apiKey?: string | undefined;
        baseUrl?: string | undefined;
        model?: string | undefined;
    } | undefined;
    mode?: "rules" | "ai" | undefined;
    maxFailures?: number | undefined;
    minQualityScore?: number | undefined;
    requireConventionalTitle?: boolean | undefined;
    blockedTitlePatterns?: string[] | undefined;
    requireDescription?: boolean | undefined;
    minDescriptionLength?: number | undefined;
    maxDescriptionLength?: number | undefined;
    requirePrTemplate?: boolean | undefined;
    requireConventionalCommits?: boolean | undefined;
    maxCommitMessageLength?: number | undefined;
    requireCommitAuthorMatch?: boolean | undefined;
    blockedSourceBranches?: string[] | undefined;
    allowedTargetBranches?: string[] | undefined;
    blockedFilePatterns?: string[] | undefined;
    maxFilesChanged?: number | undefined;
    maxAdditions?: number | undefined;
    minAccountAgeDays?: number | undefined;
    detectSpamUsernames?: boolean | undefined;
    detectExcessiveComments?: boolean | undefined;
    detectHallucinatedImports?: boolean | undefined;
    maxEmojiCount?: number | undefined;
    closePr?: boolean | undefined;
    addLabel?: string | undefined;
    commentOnPr?: boolean | undefined;
    exemptUsers?: string[] | undefined;
    exemptBots?: boolean | undefined;
    exemptDraftPrs?: boolean | undefined;
    exemptLabels?: string[] | undefined;
}>;
export type Config = z.infer<typeof ConfigSchema>;
export declare function buildConfig(getInput: (name: string) => string): Config;
export declare function buildConfigFromEnv(): Config;
//# sourceMappingURL=schema.d.ts.map